name: Build lambda

on:
  workflow_call:
    inputs:
      lambda-name: #lambda-backoffice
        required: true
        type: string
      test-project: #StreetNameRegistry.Tests
        required: false
        type: string
      build-project: #StreetNameRegistry.Api.BackOffice.Handlers.Lambda
        required: true
        type: string
      semver:
        required: true
        type: string
      runtime:
        required: false
        type: string
      dotnet-version:
        required: false
        type: string

jobs:
  build-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Check version
        shell: bash
        run: echo $SEMVER
        env:
          SEMVER: ${{ inputs.semver }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Parse repository name
        run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV
        shell: bash

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: .NET version
        shell: bash
        run: dotnet --info

      - name: Restore dotnet tools
        shell: bash
        run: |
          dotnet tool restore

      - name: Dotnet restore tests
        if: ${{ inputs.test-project != '' && inputs.test-project != 'none' }}
        shell: bash
        run: dotnet restore test/${{ inputs.test-project }} --runtime $RUNTIME
        env:
          RUNTIME: ${{ inputs.runtime || 'linux-x64' }}

      - name: Dotnet build tests
        if: ${{ inputs.test-project != '' && inputs.test-project != 'none' }}
        shell: bash
        run: dotnet build --no-restore --runtime $RUNTIME --self-contained test/${{ inputs.test-project }}
        env:
          RUNTIME: ${{ inputs.runtime || 'linux-x64' }}

      - name: Run all tests
        if: ${{ inputs.test-project != '' && inputs.test-project != 'none' }}
        run: dotnet test test/${{ inputs.test-project }}

      - name: Package lambda
        if: inputs.semver != 'none'
        shell: bash
        run: cd src/${{ inputs.build-project }} && dotnet lambda package --region eu-west-1        

      - name: Upload Lambda
        if: inputs.semver != 'none'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.lambda-name }}-${{ inputs.semver }}
          path: src/${{ inputs.build-project }}/bin/Release/net7.0/${{ inputs.build-project }}.zip
